### ISSUE TITLE
Allow hyphenate generated names

### ISSUE THREAD

**Issue by daffl** [feathersjs/generator-feathers#113]
When the name is also inserted into the code it needs to be `_.kebabCased`.

**Comment by toddgeist** [comment]
I was just looking this
https://github.com/feathersjs/generator-feathers/blob/master/generators/service/index.js#L8-L19
Looks like you could use inflect also and it's already in the module

`inflect.camelize('message_properties', false); // === 'messageProperties' `

**Comment by ekryski** [comment]
We're already doing this [for hooks](https://github.com/feathersjs/generator-feathers/blob/master/generators/hook/index.js#L126) we just forgot to add it for services (and probably models as well).

**Comment by toddgeist** [comment]
I'll take a stab at this one.  Doesn't look to tough.  I think I just need to add a test here.

https://github.com/feathersjs/generator-feathers/blob/master/test/transform.test.js#L6-L26
