### ISSUE TITLE
Investigate moving services/authentication

### ISSUE THREAD

**Issue by daffl** [feathersjs/generator-feathers#122]
Since it really is just configuring a plugin this can be confusing why it is in services (see https://github.com/feathersjs/feathers-authentication/issues/173#issuecomment-215622497)

**Comment by ekryski** [comment]
You and just discussed in Slack but I don't think it's really an issue with the code structure. It's more that it's not clear what was causing the error.

Maybe we can detect when a route has multiple services registered and throw an error.
