### ISSUE TITLE
Remove api versioning at service level

### ISSUE THREAD

**Issue by ekryski** [feathersjs/generator-feathers#13]
Now that https://github.com/feathersjs/feathers/issues/199 has been fixed. A better pattern for versioning APIs is to:

a) Have an entirely separate service (preferred)
b) mount a sub-app for the API version

Therefore, the generator shouldn't be doing this at the service level.

**Comment by daffl** [comment]
There is PR #14 for this that probably should be double checked before merging.

**Comment by ekryski** [comment]
:+1: I'll check it right away here.
