### ISSUE TITLE
TypeError after `npm link`

### ISSUE THREAD

**Issue by toddgeist** [feathersjs/generator-feathers#134]
If you follow the docs for contributing, it says to use npm link to symlink your local project as the global generator.  As soon as you do this you can no longer use `yo feathers`. You will get a type error
![nz2htrbeia](https://cloud.githubusercontent.com/assets/316792/15276632/878c1028-1aa2-11e6-9cea-4faf6395889f.gif)

There is a good chance I have missed something about how this is supposed to work. But my impression was that after using npm link, I would be able to use yo feathers to test and build the new features I wanted to add to the generator.

Have I misunderstood.  Or is there something more I have to do besides npm link.

**Comment by wkw** [comment]
What if you reference a specific generator, such as:
`yo feathers:app`
Does that work?

**Comment by daffl** [comment]
This looks like the change made in #132. If you `npm ls --depth 0` in the linked repository, does it have `yeoman-generator@^0.23.0` or a previous version?

**Comment by toddgeist** [comment]
it has  `yeoman-generator@0.23.3`

**Comment by toddgeist** [comment]
`yo feathers:app` has the same result

**Comment by toddgeist** [comment]
ugh---  might be this
http://stackoverflow.com/questions/37193740/error-unhandled-error-event-after-running-yo-generator
checking...

Yup just needed to upgrade Yo.  Sorry or the noise.!

**Comment by daffl** [comment]
Good to know. I was just about to double check this. Thanks for reporting though!
