### ISSUE TITLE
Command to list application services and its hooks names

### ISSUE THREAD

**Issue by alnour-altegani** [feathersjs/generator-feathers#139]
hi every body

is there any way to list all services with its all before and after hooks names in table like in [cli-table2](https://www.npmjs.com/package/cli-table2) ? like in 
![cli-table-feathers](https://cloud.githubusercontent.com/assets/6137428/15632544/524070f6-259e-11e6-81d4-9cf144f369ae.png)

in this photo I was trying to make this command by my self . but the problem is many hooks functions are called anonymously . 

**the benefit of this is when a developer want to see high overview of an API made with feathers then a command like this will be helpful .**

**Comment by daffl** [comment]
Currently I don't think there is a way except with a static code analysis. We might be able to tackle this with the generator update or later with a totally different API generator.

**Comment by ekryski** [comment]
I think this will be much more doable with the new stuff that coming with [feathers-bootstrap](https://github.com/feathersjs/feathers-bootstrap/) and the new CLI.

**Comment by ekryski** [comment]
Going to close this in favour of tracking it in the CLI. https://github.com/feathersjs/feathers-cli/issues/30

**Comment by alnour-altegani** [comment]
@daffl what about the **global hooks** ?

@ekryski is there any road map for *feathers-cli* and *feathers-generator* **new futures** ? 
the feather-bootstrap seems so cool :+1:
