### ISSUE TITLE
Plugin-based generation?

### ISSUE THREAD

**Issue by Qard** [feathersjs/generator-feathers#151]
So in Rails the generation system supports external ruby gems extending the generation pipeline with extra stuff. A good example is when you install rspec it'll then be able to generate rspec tests when you do a scaffold generate. Perhaps we could try a similar idea with some sort of generator config file where you can register other plugins? Something like this:

```js
// src/generate.js
const generator = require('generator-feathers')
module.exports = generator()
  .use(require('feathers-generator-some-test-lib'))
  .use(require('feathers-generator-some-database-lib'))
```

The data included in what gets exported by the plugins could include a unique name, so plugins could detect presence of each other and change their own behaviour. If a test library plugin sees the mongodb model plugin, it could know to use mongo models in the tests it generates.

**Comment by marshallswain** [comment]
I believe that this will be supported with the new version of the generator being developed right now.

**Comment by daffl** [comment]
Yes. It is using [Metalsmith](http://www.metalsmith.io/) and we will probably have each plugin also provide its own generator. Basic app generation works but we still have to hash out how it will look and work.

**Comment by ekryski** [comment]
Going to close in favour of tracking on the CLI https://github.com/feathersjs/feathers-cli/issues/38.
