### ISSUE TITLE
Make directory structure configurable

### ISSUE THREAD

**Issue by ForsakenHarmony** [feathersjs/generator-feathers#158]
This is only a minor problem of course, but it can still be annoying

I have two more subfolders in the `src` folder being `server` and `client` 
The generator, having hardcoded paths always generates into `src` instead of `src/server` 

I'm not sure if it's possible to fix this on your side, maybe use the `main` property in the `package.json` file

sorry if there's already another issue on this, couldn't find anything

**Comment by gregegan** [comment]
👍
