### ISSUE TITLE
RethinkDB configuration values overwritten when generating new service

### ISSUE THREAD

**Issue by luke3butler** [feathersjs/generator-feathers#174]
The generator should look to see if RethinkDB connection settings exist in the configuration, and not prompt the user to re-enter a connection string.

**Comment by daffl** [comment]
Looking into it. It used to work but might've gotten lost in some of the generator changes @ekryski made.

**Comment by luke3butler** [comment]
This functionality is clearly missing by looking at the `when` function [here](https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/index.js#236).
The "string" checking that works for the other databases won't work for RethinkDB since it's an object.

I probably should have broken up #175 into two separate commits since that PR also solves this.
