### ISSUE TITLE
Set package.json author and license according to npm/git 

### ISSUE THREAD

**Issue by OmgImAlexis** [feathersjs/generator-feathers#183]
The author section of package.json should be added like npm does with `Joe <email@example.com>` or `author: { 'name': 'Joe', email: 'email@example.com' }` instead of just adding an empty object. [Yeoman does support this](https://github.com/yeoman/generator/pull/314/files).

The same goes for the license it should be either prompted or check the git/npm settings.

I'd also be nice to have indentation and testing library as prompts.

**Comment by daffl** [comment]
I think that makes sense. Is there any documentation on how this is used?

As for the other point, I wouldn't want to add too many more prompts especially for style questions. For indentation you can just change it after in the `.eslintrc.json` and run with `--fix`.
For any other differing ideas about code styles the best course of action is probably to fork this repository and change it to your likings.

**Comment by OmgImAlexis** [comment]
The author info should be all here in the [Yeoman docs](http://yeoman.io/generator/actions_user.html).

With the indentation could you not just ask, 2 spaces, 4 spaces or tabs as they're the options most people use.

**Comment by marshallswain** [comment]
The fewer the prompts, the better.  Especially when it's something like tabs/spaces and I can just run `semistandard --fix` and be done.  Testing framework makes more sense because it can be a pain to get a working setup for first-time users.
