### ISSUE TITLE
Add more junk management to gitignore

### ISSUE THREAD

**Issue by OmgImAlexis** [feathersjs/generator-feathers#184]
It'd be a good idea to add a list of junk file to gitignore to prevent temp files, etc. getting added to git.

The main ones are as follows.
```
### OSX ###
*.DS_Store
.AppleDouble
.LSOverride

# Thumbnails
._*

### Windows ###
# Windows thumbnail cache files
Thumbs.db
ehthumbs.db
ehthumbs_vista.db

# Folder config file
Desktop.ini
```

https://www.gitignore.io/api/osx%2Cwindows%2Clinux

**Comment by daffl** [comment]
Yep, just shoot a PR to https://github.com/feathersjs/generator-feathers/blob/master/generators/app/templates/_gitignore and it'll happen 😄

**Comment by OmgImAlexis** [comment]
Should I include the whole lot of just the ones I listed?
