### ISSUE TITLE
Integration with GraphQL

### ISSUE THREAD

**Issue by jay-at-avido** [feathersjs/generator-feathers#188]
It seems to me that it would be useful when generating a service with the `yo feathers:service` command one would be able to  specify if a GraphQL layer should be generated in addition to the database templates

I hope this makes sense, if not let me know.

**Comment by daffl** [comment]
I'd still be curious on how you think this should look like though.

**Comment by daffl** [comment]
Closing this issue but definitely still open for further discussion on potential GraphQL integration.
