### ISSUE TITLE
Auth: Generator should build a config object for feathers-authentication

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#2]
Selecting an auth provider should add the config for that provider to the environment configs.

![screen shot 2015-12-27 at 12 46 04 pm](https://cloud.githubusercontent.com/assets/128857/12013895/b73eca8c-acdd-11e5-95f9-408227e970b9.jpg)

Something like
```js
auth: {
  secret: 'master-token-generation-secret',
  local: {
    loginEndpoint: '/login'
  },
  facebook: {
    appId: '149b0wv1n4v4',
    secretKey: '1g444g209n'
  },
  twitter: {
    appId: '240v9ndsvn23',
    secretKey: '1g444g209n'
  }
}
```

Related to and depends on feathersjs/feathers-authentication#6.

**Comment by marshallswain** [comment]
This is fixed in the `app-architecture` branch.

**Comment by ekryski** [comment]
Still in the works but this stuff is now in `master`.

**Comment by ekryski** [comment]
Damn this is actually pretty hard with yeoman. @daffl any chance that we can change our config files to be js files rather than JSON? I need to import the strategy somehow. The typical config for OAuth is like this:

```js
"facebook": {
  "strategy": FacebookStrategy,
  "clientID": "your-facebook-client-id",
  "clientSecret": "your-facebook-client-secret",
  "permissions": {
    "scope": ["public_profile", "email"]
  }
},
```
