### ISSUE TITLE
Escape config vars on windows

### ISSUE THREAD

**Issue by ekryski** [feathersjs/generator-feathers#214]
People seem to keep running into `username` being picked up by the default Node.js `USERNAME` env var on windows. We should probably at least escape this one and set it to `//username` when the generator is run on Windows.

There are likely a few other config values we want to escape. Maybe all of them on Windows???

**Comment by daffl** [comment]
The default field is `email` so I'm not sure if we need to change anything in the generator although we might want to look into disabling the auto expansion in `feathers-configuration`?

**Comment by daffl** [comment]
I think the main problem this got missed was that the documentation for it got lost somewhere. I added it back in https://github.com/feathersjs/feathers-configuration/pull/43
