### ISSUE TITLE
Add "use strict" in src/hooks/logger.js.

### ISSUE THREAD

**Issue by kfern** [feathersjs/generator-feathers#220]
Node 4 test fails: 

```
src/hooks/logger.js:6
let message = `${hook.type}: ${hook.path} - Method: ${hook.method}`;
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```
https://travis-ci.org/kfern/test-feathers-hooks-issues-61/jobs/242702225

**Comment by daffl** [comment]
The generated application only works with Node 6 or later. It should show a warning if you are trying to use it with an older version of Node (https://github.com/feathersjs/generator-feathers/blob/master/lib/generator.js#L15).
