### ISSUE TITLE
Header or request information in hooks

### ISSUE THREAD

**Issue by kfern** [feathersjs/generator-feathers#221]
Hi :-)

As discussed in https://github.com/feathersjs/feathers-hooks/issues/61, there are differences between code generated by "feathers generate app" command and proposed solutions by @daffl and @marshallswain

**Comment by daffl** [comment]
Since this issue came up again, I am inclined to move the middleware registration _before_ the services and just add `notFound` and the error handler explicitly in `app.js`.
