### ISSUE TITLE
Sequelize 4.x Breaking Changes

### ISSUE THREAD

**Issue by dschnare** [feathersjs/generator-feathers#224]
When generating a service that uses Sequelize, the models are using the older 3.x way of defining a model.

1. Either lock down the version of Sequelize to 3.x
2. Or update the model definition template to use the new definition technique

See: http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html#breaking-changes

I'd still recommend locking down the version of Sequelize to 4.x.

**Comment by dschnare** [comment]
This appears to only affect `authentication` generator, specifically the users model.

**Comment by daffl** [comment]
Thank you! It looks like it has been updated in #216 for normal models but not for the user model so it is an easy fix we can get out with the next release.
