### ISSUE TITLE
configuration(path) correct use of feathers-configuration?

### ISSUE THREAD

**Issue by arve0** [feathersjs/generator-feathers#234]
In [the template](https://github.com/feathersjs/generator-feathers/blob/master/generators/app/templates/app.js#L24) of app.js in the app generator, path for configuration is sent as a parameter. Though, feathers-configuration states that there is a [breaking change](https://www.npmjs.com/package/feathers-configuration#migrating) from 0.3 to 0.4.

Is the template outdated?

**Comment by daffl** [comment]
That is how it works now, it has been using 0.4.x for a while. Have you have any issues?

**Comment by arve0** [comment]
Yes, `app.configure(configuration(path.join(__dirname, '..')));` in the template have no effect. So loading app.js from another dir will fail reading the config.

**Comment by arve0** [comment]
Directory layout is like this:
- root/dir/file.js containing
  ```js
  const server = require('../server/src/app')
  ```
- root/server/src/app.js, from template

**Comment by daffl** [comment]
Ah, I see, if the folder is in a deeper level this will indeed break. I think your fix in https://github.com/feathersjs/generator-feathers/pull/235 works but might cause issues if we start the app outside of the root folder.

**Comment by arve0** [comment]
> I think your fix in #235 works but might cause issues if we start the app outside of the root folder.

How would it cause issues? The parameter is not in use, as of 0.4.x.

The [documentation](https://www.npmjs.com/package/feathers-configuration#migrating) states: 

> If you are currently setting your configurations via construction arguments, you will need to move these values out of your app into these environment variables.

#235 will not fix my problem, downgrading feathers-configuration to 0.3.x will. Removing the parameter from the `configuration()` call in the template will avoid confusion, as the parameter has no effect in 0.4.x.

**Comment by daffl** [comment]
Very indeed so, thank you for the catch, will go out with the next generator release.

**Comment by matbalazsi** [comment]
>  I think your fix in #235 works but might cause issues if we start the app outside of the root folder.
How should we start the app from outside the root folder? I am trying to run the feathers app as a systemd service in ubunutu.

**Comment by daffl** [comment]
Since `@feathersjs/configuration` is just a small wrapper for [node-config](https://github.com/lorenwest/node-config) you can set the [NODE_CONFIG_DIR environment variable](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir).

**Comment by matbalazsi** [comment]
thanks!
