### ISSUE TITLE
Support passing in attributes when generating a model

### ISSUE THREAD

**Issue by ekryski** [feathersjs/generator-feathers#24]
Although valuable this may be overly complex but I'm going to put it here as a reminder for now. Definitely will not hold back Feathers 2.

**Comment by jgamedev** [comment]
+1 to this.

Maybe this implementation from another generator project might help as a reference:
https://github.com/diegohaz/generator-rest/blob/master/generators/api/index.js#L108

**Comment by daffl** [comment]
Updating a model is only maybe two lines of code and a lot of work to support in the generator. See https://github.com/feathersjs/feathers-cli/issues/52 for discussion
