### ISSUE TITLE
Generator should not add existing dependencies

### ISSUE THREAD

**Issue by teddy-error** [feathersjs/generator-feathers#242]
When generating a service, the generator does not check for the existence of dependencies within `package.json` which results in an extraneous re-installation of packages with Yarn:
```
❯ fthrz yarn list | grep sequelize
├─ feathers-sequelize@2.0.1
├─ sequelize@4.2.1

❯ fthrz feathers g service
? What kind of service is it? Sequelize
...
? Which database are you connecting to? MySQL
   create src/services/apples/apples.service.js
    force src/services/index.js
   create src/models/apples.model.js
   create src/services/apples/apples.hooks.js
   create src/services/apples/apples.filters.js
   create test/services/apples.test.js
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
└─ feathers-sequelize@2.0.1
Done in 1.87s.
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 2 new dependencies.
├─ mysql@2.13.0
└─ sequelize@4.2.1
Done in 1.72s.
```
Was the reason for not implementing this check because of the complexities of outdated packages? Otherwise, I wouldn't mind implementing a check for skipping an install.

**Comment by daffl** [comment]
We're just using Yeomans infrastructure (and I thought Yarn and npm would be smarter than to reinstall), I'm not sure if it's worth the effort hacking around that.

**Comment by daffl** [comment]
I'm going to close this issue. We're happy to accept a pull request for this but we're not planning on working around functionality that should either be provided at the Yeoman or the package manager (npm and Yarn) level.

**Comment by teddy-error** [comment]
Agreed. It's so surprising which is why I mistakenly assumed the generator had missed a configuration somewhere. I'll take a look at into this, @daffl .
