### ISSUE TITLE
Authentication generator incorrectly modifying project 

### ISSUE THREAD

**Issue by thngdude** [feathersjs/generator-feathers#243]
I am using macOS Sierra and followed the instructions here: https://docs.feathersjs.com/guides/step-by-step/generators/gen-authentication.html

To add authentication to a barebones app. The project structure seems to change correctly, however, the files don't seem to update correctly.

In the CLI, I ran `feathers generate authentication`, chose "local", "user" and "Mongoose" when prompted.

The result is, for example is user.model.js was generated, but there were 2 blank lines where email and password should have been added. Also, user.hooks.js was missing hashPassword(), so even if I added email and password fields manually to the user model, passwords weren't hashed.

Btw, I also tried to run `sudo feathers generate authentication` with the same result.

**Comment by eddyystop** [comment]
@daffl  ^^^

**Comment by thngdude** [comment]
Alright, I feel a bit silly writing this, but I easily resolved this: It was my bad. I didn't realize I had to select at least one option for authentication providers (with <space>). Everything's fine. Thanks, nothing to see here.
