### ISSUE TITLE
Upgrade to pg@7.x when Sequelize incompatibility is fixed

### ISSUE THREAD

**Issue by alancwoo** [feathersjs/generator-feathers#246]
[I initially posted this in the slack](https://feathersjs.slack.com/archives/C0HJE6A65/p1500379039787932) and with the help of @marshallswain we believe there may be a bug somewhere.

1. `feathers generate app`
2. `feathers generate connection`
3. `feathers generate service`

but `npm start` is giving me ` Unhandled Rejection at: Promise ... connection.query(...).on is not a function`

I've tried with rest only, rest + realtime, and with npm/yarn with no luck.

Note from @marshallswain 
> This actually looks like a Sequelize bug, but we’ll want to leave it open until we figure out a fix.
> It’s internally trying to call `.on` on a Promise, which of course isn’t going to work.

--

Note, the above does for some reason work with sqlite as the database

**Comment by marshallswain** [comment]
I can confirm that there's a problem.  It occurs after running `sequelize.sync()` in `sequelize.js`.   I don't know what changed.  It seems like others would have run into this problem, already.

**Comment by daffl** [comment]
I wasn't able to reproduce. I am using a standard homebrew MySQL installation, generate a new app, generated a Sequelize service and chose MySQL as the database.  The thing I had to do was add the driver via `yarn add mysql2` (which is a bug in the generator that we should fix) and create the database manually (`mysql -u root` then `CREATE DATABASE feathers_test`).

**Comment by DesignByOnyx** [comment]
Ugh - I found the error - it's the in `pg` module (required by sequelize when using postgres). The latest pg@7.x connection manager [no longer returns event emitters](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#breaking-changes) like it used to in earlier versions. This has been reported [here](https://github.com/sequelize/sequelize/issues/7973).

**Comment by alancwoo** [comment]
Can confirm here rolling the package back to `pg 6.x` works for me!

**Comment by daffl** [comment]
Ah, I thought it was MySQL for some reason. @marshallswain should we leave this issue open until it is fixed in pg or Sequelize? We could also change the generator to install pg@6

**Comment by marshallswain** [comment]
Let's update the generator, for sure.  I'm going to rename this issue so it better serves as a reminder to upgrade `pg` when it's fixed.
