### ISSUE TITLE
mongodb config does not seem to wait for the connection to resolve

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/generator-feathers#253]
The relevent code in src/services/monododb.js is
```javascript
  const config = app.get('mongodb');
  const promise = MongoClient.connect(config);
  app.set('mongoClient', promise);
```

My test apparently used a mongodb service before the connection was established. It looks like it threw because `app.service(...)` was undefined. It did not throw once I delayed the test with a setTimeout.

I think the main concern is that an app using mongodb may sometimes boot and sometimes not.

**Comment by daffl** [comment]
I think adding something like

```js
before(() => app.get('mongoClient'));
```

In the tests should also wait for the client to connect and run your tests reliably.

**Comment by eddyystop** [comment]
These are not mocha tests, rather some test apps. I think this should at least be documented as its a time sink to track down.

**Comment by daffl** [comment]
I wonder if there is a good way for the generator to wait for the connection before starting the server.

**Comment by eddyystop** [comment]
That is the conundrum.

One positive point is that MongoDB can only be used on the server. Can anything be done with async/await?

**Comment by daffl** [comment]
This issue was moved to feathersjs/feathers#996
