### ISSUE TITLE
Authentication: knex + sql server

### ISSUE THREAD

**Issue by dschnare** [feathersjs/generator-feathers#256]
When I use the authentication generator with Knex and SQL Server I get this error:

```
AssertionError: Trying to copy from a source that does not exist: ....../generator-feathers/generators/connection/templates/knex-mssql.js
```

It looks like the `knex-mssql.js` template is missing. However, after investigating this, knex should not actually require anything special when connecting to SQL Server. I've been able to simply provide the client 'mssql' with a `mssql://...` connection string as the `connection` option and it works as expected.

Example options:

```
{
  mssql: {
    client: 'mssql',
    connection: 'mssql://...'
  }
}
```

Proposed fix ( https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/index.js#L268 ):
```
   if (database === 'rethinkdb') {
      template = 'rethinkdb.js';
    } else if (database === 'mssql' && adapter === 'sequelize') {
      template = `${adapter}-mssql.js`;
    } else if (adapter && adapter !== 'nedb') {
      template = `${adapter}.js`;
    }
```

**Comment by daffl** [comment]
Closed via #257
