### ISSUE TITLE
Incorrect Knex client used when SQL Server chosen

### ISSUE THREAD

**Issue by dschnare** [feathersjs/generator-feathers#258]
I've noticed that when choosing knex as the adapter and SQL Server as the DB when generating a service the knex `client` is set to `tedious` and `tedious` is installed as a dependency. This is not correct. The following should take place:

1) `mssql` should be installed not `tedious`
2) the value of the `client` parameter should be set to `mssql` not `tedious`

See: http://knexjs.org/#Installation-node
Knex version 0.13.0

**Comment by daffl** [comment]
Looks like this can be fixed fairly easily by changing https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/index.js#L39
