### ISSUE TITLE
Incorrect Knex client used when choosing Postgres

### ISSUE THREAD

**Issue by dschnare** [feathersjs/generator-feathers#259]
I've noticed that when choosing knex as the adapter and Postgres as the DB when generating a service the knex `client` is set to `pg@6` and `pg` is installed as a dependency. This is not correct. The following should take place:

1) the value of the `client` parameter should be set to `pg` not `pg@6`

See: http://knexjs.org/#Installation-node
Knex version 0.13.0

Is there a reason that the `pg` module is locked at version 6.x?

**Comment by daffl** [comment]
Version 6 of `pg` is required for Sequelize. The reason is tracked in #246
