### ISSUE TITLE
The automatic generator-feathers update does not work.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/generator-feathers#264]
![generator-error](https://user-images.githubusercontent.com/1553311/29666370-fef688c4-88a5-11e7-97d6-2aba7066f170.JPG)

**Comment by eddyystop** [comment]
Run the generator. Says generator is out of date. Accept generator update. Rerun the generator.  Says generator is out of date.

**Comment by daffl** [comment]
This must be an old version of `feathers-cli` since the update check has been removed in v2. `feathers --version` should show something around `2.3.5`.

**Comment by daffl** [comment]
Were you able to verify? I definitely want to bring the update check back but the current version shouldn't show it at all.
