### ISSUE TITLE
feathers generate service vs sequelize model:create

### ISSUE THREAD

**Issue by mbt-olivier-o** [feathersjs/generator-feathers#286]
In the context of using  sequelize with feathers:
to create a model you can run 

```
 sequelize model:create --name post --attributes title:string,content:text
``` 
a model file is created accordingly in the migration folder specified  by a .sequelizerc

```
const path = require('path');

module.exports = {
  'config': path.resolve('migrations/config/config.js'),
  'migrations-path': path.resolve('migrations'),
  'seeders-path': path.resolve('migrations/seeders'),
  'models-path': path.resolve('migrations/models')
};
```
in this example you get : `/migrations/models/post`

Once the model is generated next step is to create a  service  
```
feathersjs generate service
```
another model is created under `/src/models/post.model.js`

Ideally, it would be nice when the generator is running it detects that a model is already there and either make a `require` of it or copy the table creation part and add any feathers specific.

**Comment by DesignByOnyx** [comment]
You are mixing and matching generators. You are also using the migrations code from the feathers docs (I know, I wrote it ;)).

I recommend not mixing generators. Here's why:

- Generators are merely a convenience - they're not perfect, and you are supposed to change the generated code to suit your needs. Generators cannot (and should not) check for code/files created by other generators.
- Feathers models should all be stored in one place: `src/models`
- The models path used by the migrations is `path.resolve('migrations/models')`. Have you looked in that folder? There shouldn't be any models in that folder. It loads all of the models from your application. Again, those models should be defined in `src/models`.
- Last but not least, the feathers generators will generate a model for you and register it with your app. Your migrations script will automatically see this without you needing to do anything.

**Comment by mbt-olivier-o** [comment]
@DesignByOnyx , thanks for the clarification. According to the sequelize doc it doesn't seem to be possible to create a migration without generating a model. I'm trying to come up with a best practice solution.
Should one run
 ``` 
sequelize model:create --name post --attributes title:string,content:text 
```
then delete the model file generated by sequelize and then run the `feathers generate service` to get the model?

**Comment by daffl** [comment]
Sounds about right to me but maybe @DesignByOnyx can weight in again. I'm going to close this issue though since the generator will stay the way it is for the moment.

**Comment by mkozjak** [comment]
Maybe I'm missing something, but when we create a service via feathersjs' cli, we only get a `text` column in the database. Can we define columns when using the generator?

**Comment by daffl** [comment]
The generator is supposed to get you set up quickly but other than the initial model template and connection setup it will not do anything specific to the ORM/database you chose. In most ORMs adding columns is a line or two of code.

**Comment by mkozjak** [comment]
Ok, makes sense!

**Comment by huesoamz** [comment]
But there is a way to to import all columns to the model? instead of only gettin a "text" column? I have a lot of tables with a lots of columns, there will be a mess write all on hand, instead of having a cli command like loopback have as "discover" there is something similar in feathersjs?
