### ISSUE TITLE
knex table name should snake_case

### ISSUE THREAD

**Issue by nueko** [feathersjs/generator-feathers#288]
Hi, the generated model for knex use kebab-case. it should be snake_case.

**Comment by daffl** [comment]
A PR changing `kebabName` in https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/model/knex.js and https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/model/knex-user.js to `snakeName` would be welcome.

**Comment by nueko** [comment]
done #289 but forgot to add `fix` keyword

**Comment by daffl** [comment]
Closed via #289
