### ISSUE TITLE
Generator auto updates packages

### ISSUE THREAD

**Issue by chris-garrett** [feathersjs/generator-feathers#292]
When generating a new service today I see that it's also updated sequelize. There is *no* scenario that I can think of where I would want this to happen. 

```
-    "sequelize": "^4.17.0",
+    "sequelize": "^4.18.0",
```

**Comment by daffl** [comment]
According to [Semantic versioning](http://semver.org/) those two versions are compatible with no breaking changes so upgrading shouldn't cause any issues (and if it does should be reported as a bug with Sequelize).

I wonder if it would reinstall new major versions though - we might have to add a version range.

**Comment by chris-garrett** [comment]
That's a good point, in this test repo I forgot to pin the versions. 

With an explicit version it's still getting upgraded: 
```
-    "sequelize": "4.17.0",
+    "sequelize": "^4.18.0",
```
