### ISSUE TITLE
Add cors options to generator.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#3]
Based on this express plugin: https://www.npmjs.com/package/cors

This would allow one of three options:
1. No cors
2. cors from whitelisted domains. (Ask for domains next.)
3. cors from all domains.

OPTIONS requests would be enabled by default, since it would be a single line to remove it.

**Comment by ekryski** [comment]
:+1: Yup this is totally fair. I'd think it's pretty common to need to enable some form of CORs with micro services ha ha.

**Comment by marshallswain** [comment]
This is fixed in the `app-architecture` branch.
