### ISSUE TITLE
Sub generators break when using michael jackson script

### ISSUE THREAD

**Issue by rayfoss** [feathersjs/generator-feathers#303]
Sub generators expect you files to end in .js, but all Node's ES Modules implementations expect 
 files to end in .mjs

```
$ yo feathers:service
? What kind of service is it? NeDB
? What is the name of the service? organizations
? Which path should the service be registered on? /organizations
? Does the service require authentication? Yes
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: my-server/src/services/index.js doesn't exist
```

**Comment by daffl** [comment]
As mentioned before, you can't use ES modules with the generator yet. Even if the file extensions work the code transformations will not.

**Comment by rayfoss** [comment]
My intent was to ask if we can get started on making pull requests to support it... I see no reason not to, the change is immenent. Code sharing from server to client is a real hassle without ES modules.

**Comment by daffl** [comment]
A pull request would definitely be welcome. The code transformations are in https://github.com/feathersjs/tools (specifically https://github.com/feathersjs/tools/blob/master/lib/transform.js) now.

Not sure I'm following on the code sharing. A lot of modules (including Feathers) are using good old `require` and work fine on the client. At the moment I'd be expecting the whole `.mjs` kerfuffle to be a much bigger problem sharing code between client and server.

**Comment by rayfoss** [comment]
We still can't copy paste require based code into an ES module during development. The ideal is to have one... there are lots of annoyingly similar differences as well that make it less than trivial. Thanks for the update

**Comment by rayfoss** [comment]
This is too ahead of it's time. I've even doubled down on require based code, doing things like conditional imports, which are illegal in esm.  The tooling such as generators and weird edge case webpack plugins also don't like mjs. This is a war, not a battle. When it's time to fight it, this generator will be an important battleground for mjs in feathers.
