### ISSUE TITLE
Include operatorsAliases in sequelize connection.

### ISSUE THREAD

**Issue by DesignByOnyx** [feathersjs/generator-feathers#307]
Sequelize now recommends that operator aliases be defined so as to prevent known security issues ([read more here](http://docs.sequelizejs.com/manual/tutorial/querying.html#operators)). 

Sequelize now emits a warning if aliases are not defined. In order to suppress this warning and "follow the rules", the generator should include known aliases:

```js
const operatorsAliases = {
    $in: Op.in,
    $notIn: Op.notIn,
    $lt: Op.lt,
    $lte: Op.lte,
    $gt: Op.gt,
    $gte: Op.gte,
    $ne: Op.ne,
    $or: Op.or
  };
const sequelize = new Sequelize(connectionString, {
    dialect: 'postgres',
    logging: false,
    operatorsAliases,
    define: {
      freezeTableName: true
    }
  });
```

**Comment by daffl** [comment]
Makes sense. We'll probably have to update the adapter to use this as well right?

**Comment by DesignByOnyx** [comment]
I don't think the adaptor needs to do anything - the only operator being referenced is [`$notIn`](https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/utils.js#L53-L61). However, if we want we can create an alias for `$nin` and get rid of that section of code:

```js
const operatorsAliases = {
    ...
    $notIn: Op.notIn,
    $nin: Op.notIn, // this makes the non-standard $nin operator recognized by sequelize
    ...
};
```
