### ISSUE TITLE
Error: Cannot find module '@feathersjs/authentication' after using a new generator with old project

### ISSUE THREAD

**Issue by tamerMarzouk** [feathersjs/generator-feathers#308]
I installed the feathers generator v3.2.0. But when I tried to to generate a service in an older feathersjs project I keep getting the below error when I run npm start.
Error: Cannot find module '@feathersjs/authentication' 

How to use a specific generator for each project?
why do the documentation suggest to install the generator globally ?

**Comment by daffl** [comment]
You have to follow the [migration guide](https://buzzard.docs.feathersjs.com/migrating.html) by running `feathers upgrade` or update the package names manually.
