### ISSUE TITLE
Possibly remove Babel from generated app

### ISSUE THREAD

**Issue by daffl** [feathersjs/generator-feathers#31]
I just did some tests and I think Node 5 now pretty much supports all ES6 features that we are using in the docs and the generator except for modules (which actually isn't part of the ES6 spec anyway).

Since @marshallswain already noticed slower app startup time and higher memory consumption using Babel I am proposing to just switch the generator and all documentation examples to `require` imports and syntax that is supported by latest Node.

**Comment by marshallswain** [comment]
:+1:

**Comment by daffl** [comment]
This will also fix the demo problem submitted in https://github.com/feathersjs/feathers/issues/212. As long as you are using the latest Node everything should work. In older Node versions you'll just have to use ES5 (which we will mention in the docs).

**Comment by ekryski** [comment]
k I'll convert this today.

**Comment by daffl** [comment]
We probably need to check `process.version` and throw an error if it is not Node 5 though. Or enable Babel in that case but I'm not sure if it's worth the effort.

**Comment by marshallswain** [comment]
Let's just provide instructions on how they can add Babel if they need another Node version.

**Comment by sscaff1** [comment]
@marshallswain @daffl Were the instructions on how we can add Babel pack ever added somewhere?

**Comment by marshallswain** [comment]
I'm pretty sure they haven't been added, yet.  I created this issue for it, yesterday: https://github.com/feathersjs/feathers-docs/issues/105

**Comment by daffl** [comment]
We should definitely have a "Setting up guide" (that most importantly mentions to use nvm and also includes Babel) but the Babel setup would really just be a copy of https://babeljs.io/docs/setup (CLI or require hook). There is nothing  Feathers specific that needs to be done.
