### ISSUE TITLE
Typo: "typ" should be "type"

### ISSUE THREAD

**Issue by morphatic** [feathersjs/generator-feathers#322]
https://github.com/feathersjs/generator-feathers/blob/fa2c712b534d338d16c225b0ce3127c3cede6c03/generators/authentication/index.js#L79

**Comment by daffl** [comment]
This is correct. See [the JWT spec](https://tools.ietf.org/html/rfc7519#section-5.1).

**Comment by morphatic** [comment]
Oh. Then it's wrong here: https://docs.feathersjs.com/guides/auth/recipe.oauth-basic.html

I noticed the difference between the two and just assumed (incorrectly) that the weirdly-spelled one was wrong. :)

**Comment by daffl** [comment]
Ah, good catch, can you submit a PR that fixes it (and maybe check if there is any other references like that)?

**Comment by morphatic** [comment]
submitted #956

**Comment by daffl** [comment]
Fixed via https://github.com/feathersjs/docs/pull/956
