### ISSUE TITLE
Support selecting plugins

### ISSUE THREAD

**Issue by ekryski** [feathersjs/generator-feathers#33]
Currently when given the option of auth we only support local but with `feathers-authentication@v1.0.0` around the corner we will now be able to support any OAuth2 provider. Since Yeoman is composable I'm wondering if instead of having monster `switch` statements we start to defer to a sub generator(s) for installing plugins.

That way, even after a developer has scaffolded an app they could run `yo feathers:plugin` and then choose which type of plugin they want to install. This will come in very handy when we start rolling out other plugins for things like payment, mailing, messaging, etc.

If it's broken down nicely (ie. `feathers:plugin:auth`, `feathers:plugin:payment`, etc.) we _should_ be able to be a bit smarter and configure the plugin automatically/provide sane defaults/prompts that are more tailored to workflow for the type of plugin the dev is installing.

We may even be able to dynamically list available plugins by searching npm for the `feathers-plugin` keyword.

**Comment by hnordt** [comment]
Everyone is using npm, it's popular, easy to use and consume, why just not build a special page that list all packages that have a specific tag? Hooks => #feathersjshook, Services => #feathersjsservice

**Comment by ekryski** [comment]
@hnordt I think you misunderstood. This is for actually installing the plugin into your app. Like how authentication works.

**Comment by daffl** [comment]
This will be supported for core plugins (authentication, databases, models) but we probably won't be adding any additional plugins to the generator. Most of them are easy enough to configure yourself.
