### ISSUE TITLE
Enhancement Request: Allow for the name spacing of services using dot notation

### ISSUE THREAD

**Issue by richbai90** [feathersjs/generator-feathers#341]
I'm curious if anyone else is using feathers in this way, but in my application I like to group my services by a common purpose. For instance I might have all my Session services at a session/service endpoint. The current behavior in the generator is that when I try to specify that separation using dot notation, IE `feathers generate service foo.bar` it changes the name to `foo-bar` and the default path is `/foo-bar`. Preferably I'd like the path to be `/foo/bar` and the services to be grouped under `services/foo/bar` I already have a fork of the yo generator that does this, and I'd gladly submit a PR if I'm not the only use case.

**Comment by daffl** [comment]
I think `/` separated would make sense but yes, allowing the generator to put things into sub folders is something that would be great to support. If you have done the work already in a fork, definitely put up the PR so we can discuss it there.

**Comment by richbai90** [comment]
All checks are passing for PR #342
