### ISSUE TITLE
Typo in channels.js

### ISSUE THREAD

**Issue by temowemo** [feathersjs/generator-feathers#352]
Hello, I found a small typo in `/generators/app/templates/src/channels.js`

On line 51 there is a comment:
`// e..g the publish the `users` service `created` event to the `admins` channel`
I am pretty sure is supposed to be:
`// e.g. the publish the `users` service `created` event to the `admins` channel`

I know this is not a big deal but I have been wanting to make my first pull request and I thought that this would be a good opportunity to do so. Would anyone be opposed to this?

**Comment by daffl** [comment]
Of course not, pull requests are always welcome, thank you for wanting to contribute! 😄

You should be able to edit the file directly at https://github.com/feathersjs/generator-feathers/blob/master/generators/app/templates/src/channels.js and it will automatically submit a pull request when you save. This is usually the quickest way to submit comment and documentation changes that don't modify any code (which you probably want to test locally first).

**Comment by temowemo** [comment]
Okay thank you! I will do that. :grin:

**Comment by daffl** [comment]
Closed via #353. Thank you for the PR!

**Comment by daffl** [comment]
Closed via #353. Thank you for the PR!
