### ISSUE TITLE
Typo in authentication config

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs/generator-feathers#361]
I believe there is a typo on this line. Should be `type`

https://github.com/feathersjs/generator-feathers/blob/e7d9eb90e4d856f273fb9883977932d3a311b45a/generators/authentication/index.js#L79

**Comment by daffl** [comment]
This - understandably - comes up from time to time but it is the ["typ" (Type) Header Parameter](https://tools.ietf.org/html/rfc7519#section-5.1) according to the JWT specification.
