### ISSUE TITLE
Scope not generated for Auth0 strategy

### ISSUE THREAD

**Issue by akagomez** [feathersjs/generator-feathers#364]
It isn't stated in the [auth0/passport-auth0](https://github.com/auth0/passport-auth0) documentation, but the Auth0 strategy will not return any useful profile data unless you provide a `scope`. See: https://auth0.com/docs/scopes/current#standard-claims.

Currently the generator only adds a `domain` to the Auth0 config: 

https://github.com/feathersjs/generator-feathers/blob/15aa20fa73c9e07e167b68c26b72ff119da1364a/generators/authentication/index.js#L109

However, we probably want to also include a `scope` in the same way we do for the [Google](https://github.com/feathersjs/generator-feathers/blob/15aa20fa73c9e07e167b68c26b72ff119da1364a/generators/authentication/index.js#L118) and [Facebook](https://github.com/feathersjs/generator-feathers/blob/15aa20fa73c9e07e167b68c26b72ff119da1364a/generators/authentication/index.js#L113) strategies.

**Comment by daffl** [comment]
I think it definitely makes sense to at least add `profile` just like for the other strategies.
