### ISSUE TITLE
TypeError: Cannot read property 'combine' of undefined

### ISSUE THREAD

**Issue by kschluter** [feathersjs/generator-feathers#369]
Hi, I installed 3.71, I generated an app, attempted to run it and got the error in the title. It seems 3.7.1 cli generates apps that point to winston 2.6.4 package but it needs 3.0.0 to make this error dissappear.

**Comment by eddyystop** [comment]
I also ran into this Winston v3 issue.

Yeoman "sometimes" installs as an npm pacakge a version other than the latest. I get around this with `npm  cache clean --force`.  Its very annoying.

**Comment by daffl** [comment]
No idea why npm keeps and/or Yeoman acting up about this but I locked the version to 3.0 now.
