### ISSUE TITLE
Outdated README.md template

### ISSUE THREAD

**Issue by Alfredo-Delgado** [feathersjs/generator-feathers#387]
The `Scaffolding` section of the generated README.md lists `$ feathers generate model                 # Generate a new Model`.

Since this doesn't work and it's not listed under `feathers help`, I assUme that it's safe to remove that line from the template?

**Comment by daffl** [comment]
Definitely. Wondering if it should be brought back since the question keeps coming up but it would be a little more involved when generating a service (calling the model sub-generator) and for some things like Sequelize you have to `require` the model somewhere anyway.
