### ISSUE TITLE
Best practice to extend a generator

### ISSUE THREAD

**Issue by gpietro** [feathersjs/generator-feathers#399]
Hi,
I would like to extend the service generator by adding custom content to the file and use the feathers-cli package to run the command.
There is a best way to do this than forking both projects (generator-feathers and feathers-cli)?
Thanks.

**Comment by daffl** [comment]
There is currently no way to run the `feathersjs/cli` with a different generator but it is really just a very small wrapper around [Yeoman](https://yeoman.io/). So the steps for a custom generator would be

- Fork this repository
- Make your changes
- Publish it (under your namespace) or run `npm link`
- `npm install yo -g`
- `yo` and this generator should show up in the list
