### ISSUE TITLE
Move config folder inside src.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#4]
@feathersjs/core-team Anybody opposed to moving the `config` folder inside the `src` folder with the rest of the app?  We're not really configuring anything outside `src`, right?

![screen shot 2015-12-29 at 9 43 31 pm](https://cloud.githubusercontent.com/assets/128857/12046385/6dba5b94-ae75-11e5-990b-4dff285e554c.jpg)

**Comment by daffl** [comment]
I always found it nice on the top level. Configuration files are more likely to be changed by a third party and aren't really source files.

**Comment by ekryski** [comment]
Ya I say leave it. My thought was you might be referencing the config values in tests too.
