### ISSUE TITLE
add .gitignore to application generator

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/generator-feathers#40]
Maybe it makes sense to add `.gitignore` file in the application generator? In order to `node_modules` folder was not included in the repository.

![2016-02-20 1 00 42](https://cloud.githubusercontent.com/assets/557190/13190302/7530881e-d76d-11e5-908f-86b4ffd3dfa6.png)

**Comment by ekryski** [comment]
I thought we had this. I'm pretty sure I had this at some point but maybe it was removed. I'll add it back. There is some crap you have to do in order for it to work because of how npm treats `.gitignore` files.

**Comment by daffl** [comment]
It is in https://github.com/feathersjs/generator-feathers/tree/master/generators/app/templates/static but I ran into this before. For some weird reason Yeoman does not copy `.gitignore` files. It has to be called something else and renamed when copying it over.

**Comment by ekryski** [comment]
It's actually not a yeoman issue. It's npm. I fixed it somewhere before. Maybe it was in the plugin generator.

**Comment by ekryski** [comment]
Fixed with e8b0719f45c643227f4139ae545fe00b5ee3ece9
