### ISSUE TITLE
Model naming doesn't match Mongoose documentation/practices

### ISSUE THREAD

**Issue by bloomdido** [feathersjs/generator-feathers#416]
https://github.com/feathersjs/generator-feathers/issues/135 refers to using PascalCase for model names and was marked as closed, but never seemed to be implemented. Additionally, the [documentation for Mongoose models](https://mongoosejs.com/docs/models.html) states that the first param to the .model() method should be "the singular name of the collection".

While it appears that the current generator template works most of the time, updating it to match the current Mongoose best practices for model naming might be a welcome improvement.

**Comment by daffl** [comment]
Automated inflection is a big maintenance burden that can cause a lot of subsequent issues which is why the Feathers CLI does not do it. The source file can always be edited to match the desired name.
