### ISSUE TITLE
Could not find the hooks definition object while adding ../../hooks/***

### ISSUE THREAD

**Issue by ranhsd** [feathersjs/generator-feathers#419]
Hi I am getting an error after trying to generate some hook to my app. 

I already generated several hooks and everything works well but now from some reason I am getting the following error: 

![image](https://user-images.githubusercontent.com/3685671/58401708-345ce200-8067-11e9-8bfd-0a9ce87e0e9f.png)

I tried to check for paths but it seems that I did not change anything.

Thanks.

**Comment by eddyystop** [comment]
The generator can handle hooks which it itself generated not ones manually added. Is this the issue here?

**Comment by ranhsd** [comment]
Hi @eddyystop 

Actually all hooks has been generated using the generator. 

The only thing I did is to add some code to the app.hooks.js in order to run the same code for all the services.

**Comment by daffl** [comment]
That is the error. This version of the generator expects the file it is supposed to add the hooks to only include a single object definition and nothing else.

**Comment by ranhsd** [comment]
Hi @daffl Thanks for your response. 

So what should I do? 
Remove the code from app.hooks.js ?

Earlier I tried to do so and I still got the error

**Comment by ranhsd** [comment]
@daffl So what I decided is to choose **I will add it myself** option and then manually add it to where I want and it works.

**Comment by bartduisters** [comment]
Bumped into the same error. I expected the generator to just add it as an extra hook.
Manually it is.

**Comment by josepcrespo** [comment]
Having a call to `console.log` in any `* .hook.js` file of any service, also causes this error. At least, in my case, I had a call to `console.log` between the constants declaration and `module.exports`, in the file `user.hooks.js` and it caused this error. Simply removing the call to `console.log` the problem was gone.

**Comment by zanzara** [comment]
Bumped aswell into the same error.
Not even any `console.log`  does generate this error.  I also appears if you have any own hooks in there as i.e.:
```
  create: [
    firstHoook(),
    c => {accountService(c.app).notifier(...)  },
    newHook()
  ]
```
I commented  `c => ...`  out for a moment, and then I could create a hook with cli again
