### ISSUE TITLE
Remove inflection and ask for service path

### ISSUE THREAD

**Issue by daffl** [feathersjs/generator-feathers#44]
I saw that the service generator does automatic pluralization. I think we should instead ask for the service path if someone wants it to be different than the service name (and just set it as the same by default).

**Comment by ekryski** [comment]
I know that you're against inflection but that lib is actually pretty robust. People can always change the service paths after the fact if they need to. Maybe we can leave this issue open for a bit to see if anyone really needs that change before we implement it? So far I haven't had any issues with it at all.

**Comment by daffl** [comment]
Yeah I'm really not a big fan of it although it's a little better when it is generated so you can always change it. We could add least add a simple prompt with the inflected name so that you can change it when generating it if you want?

**Comment by ekryski** [comment]
I'm down with that. Basically just another enter key.
