### ISSUE TITLE
Database setup still needed.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#5]
The question is in place, but the code isn't, yet.

**Comment by daffl** [comment]
Indeed it isn't. I'm wondering what would be the best way to do this. The adapters work quite differently in terms of initialization. How do we share e.g. a MongoDB or Sequelize DB connection?

**Comment by ekryski** [comment]
Ya this is a bit tricky. Even the way we have the question laid out we ask what type of database they want to use. Do we then choose what we think is the best ORM or adapter based on the person's selection?

With that said, I'm wondering if we can have initialization templates for each ORM or adapter, whereby based on the users selection we just copy that in place. Similar to our `example` in each adapter repo.

I think in order for this to happen we'll need to have all the adapters have the same interface for requiring and initialization. This will also make things familiar for people and easy for them to switch or add additional data stores. Currently, they are a bit divergent so I think we need to come up with a spec for how they should be initialized.

**Comment by ekryski** [comment]
Closed by #7.
