### ISSUE TITLE
errors.handler is not a function

### ISSUE THREAD

**Issue by samuel-kollat** [feathersjs/generator-feathers#52]
After clean run of
`yo feathers`
and
`npm start`
following error is presented

```
app.use(errors.handler());
                 ^
TypeError: errors.handler is not a function
```

Fix should be:
**src/middleware/index.js**
```
line 3: const errors = require('feathers-errors/handler');
```
and then
```
line 15: app.use(errors());
```

**Comment by ekryski** [comment]
sorry we just pushed a new version of `feathers-errors`. Fix incoming. Maybe we need to freeze our generator versions.

**Comment by ekryski** [comment]
@samuel-kollat try the latest v0.6.4. It should be fixed. Sorry it took so long I took the opportunity to fix a bunch of other bugs.

**Comment by samuel-kollat** [comment]
@ekryski Thank you for quick response & fix :)
