### ISSUE TITLE
Generate services for each adapter.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#6]
- [x] Memory
 - [x] Sequelize
 - [x] Mongoose
 - [x] NeDB
 - [x] Waterline

**Comment by ekryski** [comment]
Closed by #7.

**Comment by sajov** [comment]
any plans to integrate waterline? thx

**Comment by daffl** [comment]
Nobody in the core team is currently using Waterline. If nobody else takes on adding it to the generator you will have to stick with using it manually.
