### ISSUE TITLE
New service generator does not prompt for authentication if default config is JavaScript module

### ISSUE THREAD

**Issue by EliSadaka** [feathersjs/generator-feathers#618]
When using a JavaScript module for the default app configuration instead of a JSON file, the new service generator does not prompt the user with the "Does the service require authentication?" prompt. This is because [the generator only retrieves the default config if it is a JSON file](https://github.com/feathersjs/generator-feathers/blob/66baed47d52c571d521d6660b31b168197526caa/lib/generator.js#L13), and it uses this config to determine [whether to display the auth prompt](https://github.com/feathersjs/generator-feathers/blob/51778983c5aea0f3617e43d81dccf823431b10ea/generators/service/index.js#L67).

**Comment by daffl** [comment]
This is fixed in the [new CLI](https://dove.feathersjs.com/guides/whats-new-in-dove.html#rebuilt-cli)
