### ISSUE TITLE
Support generating basic front ends

### ISSUE THREAD

**Issue by ekryski** [feathersjs/generator-feathers#73]
Not sure what the scope of this would be but it would be really nice to optionally generate a React, Angular, or Vue front end that includes Feathers client and sets up a basic app. The biggest thing I think, is the packager config. Giving people a sane default for Babel and/or Webpack, browserify, etc would be nice.

**Comment by anguskwan** [comment]
looking forward to that!  😋

**Comment by daffl** [comment]
For this we also decided that it is out of the scope of the generator. There are [some great frontend starters](https://docs.feathersjs.com/why/showcase.html) kicking around already.
