### ISSUE TITLE
Mongoose and Sequelize Models should have correct fields generated based on the auth providers configured

### ISSUE THREAD

**Issue by catalinmiron** [feathersjs/generator-feathers#75]
Hi guys,

I made the `local` strategy but now I want to use `Facebook` strategy.

I added the facebook login, clientId, clientSecret in place and when I'm going to `localhost:3030/auth/facebook` the callback now has the access_token `http://localhost:3030/auth/facebook/callback?code=generated_code&state=true#_=_` but I'm not logged in the app.

![image](https://cloud.githubusercontent.com/assets/2805320/13853021/87664392-ec6d-11e5-80c4-b70aae186cdf.png)

__terminal output__

```bash
Feathers application started on localhost:3030
error: (400) Route: /auth/facebook/callback?code=generated_code&state=true - user validation failed
info: BadRequest: user validation failed
    at Object.construct (/user/feathers-test/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.reflect.construct.js:22:24)
    at BadRequest.ExtendableBuiltin (/user/feathers-test/node_modules/feathers-errors/lib/index.js:21:28)
    at BadRequest.FeathersError (/user/feathers-test/node_modules/feathers-errors/lib/index.js:99:87)
    at new BadRequest (/user/feathers-test/node_modules/feathers-errors/lib/index.js:139:79)
    at errorHandler (/user/feathers-test/node_modules/feathers-mongoose/lib/error-handler.js:23:25)
    at run (/user/feathers-test/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /user/feathers-test/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/user/feathers-test/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
    at doNTCallback0 (node.js:408:9)
    at process._tickDomainCallback (node.js:378:13)

```

**Comment by ekryski** [comment]
@catalinmiron any chance you can post a link to your project somewhere?

**Comment by catalinmiron** [comment]
It's just on my local machine. I got it working usign NeDB.. but no luck usign MongoDB.

**Comment by ekryski** [comment]
I think it might be related to this issue https://github.com/feathersjs/feathers-authentication/issues/107.

**Comment by ekryski** [comment]
@catalinmiron If you can push your mongo example to a github repo that would be super helpful.

**Comment by catalinmiron** [comment]
there's nothing fancy, just the `yo feather` with facebook login and mongoDB. I haven't changed the app.js or something else. Just the basic boilerplate. What I'm asking is that should this work by default or should I add some code to this boilerplate in order to achieve FB(other oAuth) working?

**Comment by ekryski** [comment]
@catalinmiron it should work just fine. I'll double check it, We haven't set up automated tests for the OAuth stuff yet because we need to be careful we don't publish keys. You created a facebook app and everything? When you went to `/auth/facebook` it redirected and prompted you for authorization and you authorized your app?

**Comment by catalinmiron** [comment]
Yes, the setup is done right. Once the callback like `localhost:3030/auth/facebook/callback?code={{access_token}} I got the Oh no! Something went wrong in the browser and the following error in terminal

```
Feathers application started on localhost:3030
error: (400) Route: /auth/facebook/callback?code=generated_code&state=true - user validation failed
info: BadRequest: user validation failed
[...]
```

**Comment by catalinmiron** [comment]
So your setup is using the default boierplate that `yo feathers` generates with MongoDB and Facebook login?

**Comment by ekryski** [comment]
@catalinmiron Ah fuck. I was able to reproduce it. It's because your mongoose model `src/services/user/user-model.js` is expecting an email and password value. Make your model look like this:

```js
'use strict';

// user-model.js - A mongoose model
// 
// See http://mongoosejs.com/docs/models.html
// for more of what you can do here.

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const userSchema = new Schema({
  facebookId: { type: String },
  facebook: { type: Schema.Types.Mixed },
  createdAt: { type: Date, 'default': Date.now },
  updatedAt: { type: Date, 'default': Date.now }
});

const userModel = mongoose.model('user', userSchema);

module.exports = userModel;
```

restart your server and it will work.

We need to fix this and have 3 options:

- don't make those fields required and set the OAuth fields on the user according to the provider's chosen
- don't add `email` and `password` fields to the model automatically when not using local auth
- document it somewhere (probably the OAuth guide that is yet to be complete)

Maybe a combination of those. I'm going to rename this issue. Sorry about that @catalinmiron!
