### ISSUE TITLE
Generated hook tests don't pass

### ISSUE THREAD

**Issue by ekryski** [feathersjs/generator-feathers#76]
The basic test generated should probably just be this for now:

```js
describe('message process hook', () => {
  it('returns a function', () => {
    var hook = process();
    assert.equal(typeof hook, 'function');
  });
});
```

**Comment by daffl** [comment]
This is odd because the tests of a generated hook are set up to run in CI (see https://github.com/feathersjs/generator-feathers/blob/master/test/generators.test.js#L69)

**Comment by daffl** [comment]
I just verified that newly generated hook tests work. Let's reopen if I missed something.
