### ISSUE TITLE
Allow empty values for CORS domains

### ISSUE THREAD

**Issue by DesignByOnyx** [feathersjs/generator-feathers#85]
I know our project will need CORS support, but I don't know the domain names yet and don't want to use an asterisk. I mostly want yeoman to set up everything so I can plug in the domains later. But leaving the value blank causes the task to fail - specifically at this line: 

https://github.com/feathersjs/generator-feathers/blob/master/generators/app/templates/config.default.json#L26

**Comment by daffl** [comment]
Can the whitelist just contain `*`?

**Comment by ekryski** [comment]
@DesignByOnyx I think what @daffl what getting as is just put `*` as the value for your whitelist and then you can just change the whitelist arrays. Either that or just use `localhost` for the value. I think those should work.

**Comment by ekryski** [comment]
I'm going to close to this but that doesn't work for you @DesignByOnyx then we can re-open it and we'll talk about a different solution.

**Comment by DesignByOnyx** [comment]
It's fine to close it. Point was I just don't think an empty value should break the initial generation  of an app. It was my first time ever using the generator and it error'd and I had to run it a second time - thought you guys should know. Maybe the generator can default to `*` if the prompt value is empty. I dunno. Thanks for such a great tool though. Everything has been very pleasant so far.

**Comment by daffl** [comment]
You are right and it is an easy fix. This was also brought up in https://github.com/feathersjs/generator-feathers/issues/85

**Comment by ekryski** [comment]
@DesignByOnyx yup thanks for bringing that up. We tend to close issues fast so that they don't back up. We are more than willing to re-open ones where there are legit problems.

**Comment by daffl** [comment]
Fixed in `v0.6.20`
