### ISSUE TITLE
use mongodb instead of mongoose when yo feathers:service and select mongodb

### ISSUE THREAD

**Issue by beeplin** [feathersjs/generator-feathers#89]
currently when yo feathers:service and select mongodb, mongoose adapter is used instead of mongo.

**Comment by ekryski** [comment]
That is the intended behaviour. If you want to use [feathers-mongodb](https://github.com/feathersjs/feathers-mongodb) you need to do that yourself. We are being opinionated on what we think is the best database adapter is for people.

**Comment by beeplin** [comment]
got it. I realized that the callback syntax of original mongodb driver is really giving me headache...

**Comment by ekryski** [comment]
@beeplin ya that's the main reason that we are choosing mongoose over the raw mongodb wrapper. You can however use promises with the mongodb driver now.

**Comment by beeplin** [comment]
hmmm, I mean in the raw mongodb wrapper you have to call `mongoClient.connect` in an async way to get the `db` object which is to be used when doing:
```
  app.use('/messages', service({
    Model: db.collection('messages')
  }));
```
so i have to write the following code altogether:
```
MongoClient.connect('mongodb://localhost:27017/feathers').then(function(db){
  app.use('/messages', service({
    Model: db.collection('messages')
  }));
```
and cannot extract the `app.use` part and put it into `/src/service/message` as the `yo feathers:service` does.

**Comment by ekryski** [comment]
Yes, that's why they aren't in the generator. We didn't spend the time figuring out how to shoe-horn mongodb and waterline (both of which have async connections) into the code structure the generator creates.

That's left up to you to sort out. You could look at trying to to resolve the promise with the `db` object. If you come up with something let us know!

**Comment by beeplin** [comment]
Sure. Thank you for the quick reply. I really appreciate all the works around feathers. Amazingly cool and very helpful. 


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Eric Kryski <notifications@github.com>
时间：周三 3月23日 00:22
收件人：feathersjs/generator-feathers <generator-feathers@noreply.github.com>
抄送：Beep LIN <beeplin@gmail.com>
主题：Re: [generator-feathers] use mongodb instead of mongoose when yo feathers:service and select mongodb (#89)

>Yes, that's why they aren't in the generator. We didn't spend the time figuring out how to shoe-horn mongodb and waterline (both of which have async connections) into the code structure the generator creates. That's left up to you to sort out. You could look at trying to to resolve the promise with the db object. If you come up with something let us know! —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by daffl** [comment]
It should be possible to use the generated services by moving `app.configure(services)` in `src/app.js`:

```js
MongoClient.connect('mongodb://localhost:27017/feathers').then(function(db){
  app.configure(services);
  // Do other app setup here
});
```

**Comment by beeplin** [comment]
Yeah I thought of co/generator and async await but none of them applies in this case. Your way might be the only way despite that it makes the whole structure of app.js quite different from that of other cases.
  


来自 魅族 MX5

-------- 原始邮件 --------
发件人：David Luecke <notifications@github.com>
时间：周三 3月23日 00:30
收件人：feathersjs/generator-feathers <generator-feathers@noreply.github.com>
抄送：Beep LIN <beeplin@gmail.com>
主题：Re: [generator-feathers] use mongodb instead of mongoose when yo feathers:service and select mongodb (#89)

>It should be possible to use the generated services by moving app.configure(services) in src/app.js: MongoClient.connect('mongodb://localhost:27017/feathers').then(function(db){ app.configure(services); // Do other app setup here }); —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by muhammadzklugo** [comment]
What if mongodb connection disconnects after services are registered. How can we reconnect?
