### ISSUE TITLE
Considerations for setting up model relationships with sequelize

### ISSUE THREAD

**Issue by DesignByOnyx** [feathersjs/generator-feathers#94]
I've talked about this with @daffl and am available to discuss further with anybody who has questions. But the way models and services are generated needs to be altered to allow for models to define relationships and associations with other models. This mostly just affects relational database schemas. Consider the following:

``` js
var Auther = sequelize.define('author', {
    name: Sequelize.STRING
});
var Book = sequelize.define('book', {
    title: Sequelize.STRING
});
Author.hasMany(Book);
Book.belongsTo(Author);
```

The relationship setup at the bottom is the important part. Both models need to be created, and both models need to know about one another. Only at that point can the associations actually be made, and then after it's all done the schemas should be `sync()`'d with the db.

I have implemented a fix on my current project and am still refining it a little based on my discussion with David earlier. If anybody has any questions, please feel free to ask. Here is the synopsis of what I've done:

Don't call `sync()` from within a model.
Load all models and save references in a hash table (using `sequelize.import()`)
Iterate over all models. If a static "associate" method exists, call it, passing in the hash table.
Finally call `sequelize.sync()`

**Comment by DesignByOnyx** [comment]
Sequelize recommends the following strategy for setting up associations in an Express app:

http://docs.sequelizejs.com/en/1.7.0/articles/express/#modelsindexjs

I am using this technique locally and it works like a charm. I have refactored all of my models in to a models directory, the index file looks like this:

```js
const model1 = require('./model1');
const model2 = require('./model2');
const user = require('./user');
const Sequelize = require('sequelize');

module.exports = function() {
  const app = this;

  const sequelize = new Sequelize(app.get('db_url'), {
    dialect: 'postgres',
    logging: console.log
  });

  app.set('sequelize', sequelize);

  app.configure(user);
  app.configure(model1);
  app.configure(model2);

  app.set('models', sequelize.models);

  Object.keys(sequelize.models).forEach(function(modelName) {
    if ("associate" in sequelize.models[modelName]) {
      sequelize.models[modelName].associate();
    }
  });

  sequelize.sync();
};
```

and a model looks like this:

```js
const Sequelize = require('sequelize');
const ModelHelper = require('../util/model-helper');

module.exports = function() {
  const app = this;
  const sequelize = app.get('sequelize');

  const Model1 = sequelize.define('Model1', {
    name: {
      type: Sequelize.STRING,
      allowNull: false
    }
  }, {
    freezeTableName: true,
    classMethods: {
      associate () {
        const models = app.get('models');
        MyModel.hasMany(models["Model2"]);
      }
    }
  });

  return Model1;
};
```

**Comment by marshallswain** [comment]
@DesignByOnyx thanks for doing the research on this and reporting back.  I've been meaning to get into this, but this just saved me a load of time. 🕗👍

**Comment by ekryski** [comment]
@DesignByOnyx nice man! That looks pretty great. Definitely awesome for an app where everything is in one. At some point I'll get around to seeing how it mike work with remote services. This might be a pain to change in the generator but at a minimum should probably go into a guide somewhere.

**Comment by delta1** [comment]
Trying to get my head around doing some model associations in feathers, @DesignByOnyx please help with a few questions if possible: 

- where is MyModel defined? 
- what does ModelHelper do?
- where is your models/index.js file imported/run in feathers?

**Comment by DesignByOnyx** [comment]
Hey @delta1 - sorry I am just getting to this - the email slipped through the cracks.

**where is MyModel defined?**
That's a typo and I have updated the example above. It should be `Model1` (I think `this` would even work too, so you could to `this.hasMany(Model2);`)

**what does ModelHelper do?**
That shouldn't be there either - I copied from my project and didn't delete that line. I have a model helper for doing shared some helpful things for my models ;)

**where is your models/index.js file imported/run in feathers?**
In my app file. This is kind of what it looks like:
```js
// other imports omitted for brevity
const models = require('./models');

const app = feathers();
app.configure(configuration(path.join(__dirname, '..')));

app
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(rest())
  .configure(socketio())
  .configure(hooks())
  .configure(models)
  .configure(services);
```

**Comment by delta1** [comment]
@DesignByOnyx that's awesome, thank you very much

**Comment by MidnightP** [comment]
Hi there,

This all looks so nice and I almost got it to work. However, something is wrong in the order in which I do things. Please have look at the trace of my error:

> const sequelize = app.get('sequelize')
>                         ^
> 
> TypeError: app.get is not a function
>     at module.exports (/home/pim/projects/bijlesismore/starters/Feathers-React-Starterkit/src/sequelize/models/user-model.js:18:25)
>     at EventEmitter.module.exports (/home/pim/projects/bijlesismore/starters/Feathers-React-Starterkit/src/services/user/index.js:33:12)
>     at EventEmitter.configure (/home/pim/projects/bijlesismore/starters/Feathers-React-Starterkit/node_modules/feathers/lib/application.js:138:8)
>     at EventEmitter.module.exports (/home/pim/projects/bijlesismore/starters/Feathers-React-Starterkit/src/services/index.js:52:7)
>     at EventEmitter.configure (/home/pim/projects/bijlesismore/starters/Feathers-React-Starterkit/node_modules/feathers/lib/application.js:138:8)
>     at Object.<anonymous> (/home/pim/projects/bijlesismore/starters/Feathers-React-Starterkit/src/app.js:71:4)

A model (in sequelize/models/) starts like this:

```
const Sequelize = require('sequelize')

module.exports = function() {
  const app = this
  const sequelize = app.get('sequelize')

  const User = sequelize.define('users', {
```

In services/index.js to whole shabam:
```
app.set('sequelize', sequelize)

  app.configure(listingcategories)

  app.configure(authentication)
  app.configure(user)
  app.configure(listing)
  app.configure(review)
  app.configure(category)

  app.set('models', sequelize.models)

  Object.keys(sequelize.models).forEach(function(modelName) {
    if ('associate' in sequelize.models[modelName]) {
      sequelize.models[modelName].associate()
    }
  })

  sequelize.sync({ force: true })
```
